import { WeddingConfig } from "@/types/wedding";

export const weddingConfig: WeddingConfig = {
  groom: {
    name: "Quốc Du",
    fullName: "Quốc Du",
    role: "THE GROOM",
    title: "Chú rể",
    image: "/image/wedding/chu_re.JPG",
    parents: {
      father: "Đại diện Nhà Trai",
      mother: "Gia đình Nhà Trai",
    },
    quote: "Em là bình yên, là lý do để anh muốn trở thành phiên bản tốt nhất của chính mình mỗi ngày.",
  },
  bride: {
    name: "Phương Ly",
    fullName: "Phương Ly",
    role: "THE BRIDE",
    title: "Cô dâu",
    image: "/image/wedding/co_dau.JPG",
    parents: {
      father: "Đại diện Nhà Gái",
      mother: "Gia đình Nhà Gái",
    },
    quote: "Cảm ơn vì đã luôn nắm chặt tay em, cùng em đi qua những tháng năm dịu dàng và rực rỡ nhất.",
  },
  weddingDate: "2026-11-28",
  weddingTime: "17:00",
  lunarDate: "Tức ngày 20 tháng 10 năm Bính Ngọ",
  saveTheDateText: "SAVE THE DATE",
  invitationIntro: "Trân trọng kính mời quý khách tới dự bữa tiệc thân mật mừng lễ thành hôn của chúng tôi",
  venue: {
    name: "THIÊN TRANG PALACE",
    subVenue: "Trung Tâm Tiệc Cưới & Sự Kiện Cao Cấp",
    address: "Thiên Trang Palace, TP. Cẩm Phả, Tỉnh Quảng Ninh",
    mapsUrl: "https://maps.google.com/?q=Thiên+Trang+Palace+Cẩm+Phả+Quảng+Ninh",
    embedMapsUrl: "https://maps.google.com/maps?q=Thiên+Trang+Palace+Cẩm+Phả+Quảng+Ninh&t=&z=15&ie=UTF8&iwloc=&output=embed",
  },
  events: [
    {
      time: "17:00",
      title: "ĐÓN KHÁCH & CHECK-IN",
      description: "Chụp ảnh lưu niệm & thưởng thức Welcome Drink tại sảnh tiệc",
      icon: "camera",
    },
    {
      time: "18:00",
      title: "LỄ THÀNH HÔN",
      description: "Khoảnh khắc trao nhẫn thiêng liêng & lời thề nguyện",
      icon: "ring",
    },
    {
      time: "18:30",
      title: "KHAI TIỆC MỪNG",
      description: "Thưởng thức ẩm thực & nâng ly chúc mừng hạnh phúc",
      icon: "dinner",
    },
    {
      time: "19:30",
      title: "AFTER PARTY & ÂM NHẠC",
      description: "Cắt bánh cưới, khiêu vũ và những khoảnh khắc thăng hoa",
      icon: "party",
    },
  ],
  story: {
    heading: "HÀNH TRÌNH TÌNH YÊU",
    subtitle: "Our Love Story",
    quote: "Two people. One unexpected meeting. A lifetime to go.",
    timeline: [
      {
        date: "14 . 02 . 2021",
        title: "Ngày đầu gặp gỡ",
        subtitle: "The First Glance",
        description: "Khoảnh khắc ánh mắt chạm nhau mở đầu cho một câu chuyện tình yêu dài lâu và hạnh phúc.",
      },
      {
        date: "20 . 10 . 2022",
        title: "Lời tỏ tình",
        subtitle: "Official Together",
        description: "Chúng mình chính thức nắm tay nhau bước vào một hành trình ngập tràn yêu thương.",
      },
      {
        date: "08 . 03 . 2026",
        title: "Lời cầu hôn",
        subtitle: "She Said YES!",
        description: "Một chiếc nhẫn nhỏ, một lời hẹn ước trọn đời và nụ cười hạnh phúc rạng rỡ.",
      },
      {
        date: "28 . 11 . 2026",
        title: "Ngày chung đôi",
        subtitle: "Forever Begins",
        description: "Ngày chúng mình chính thức về chung một nhà trước sự chúc phúc của gia đình và bạn bè.",
      },
    ],
  },
  gallery: [
    {
      id: "g1",
      src: "/image/wedding/T_T00859.JPG",
      alt: "Khoảnh khắc trao lời hẹn ước",
      aspectRatio: "portrait",
      caption: "A moment of eternity",
      layoutType: "full",
    },
    {
      id: "g2",
      src: "/image/wedding/T_T00033.JPG",
      alt: "Ánh mắt đắm say",
      aspectRatio: "portrait",
      caption: "In your eyes, I found my home",
      layoutType: "overlap",
    },
    {
      id: "g3",
      src: "/image/wedding/T_T00018.JPG",
      alt: "Dịu dàng bên nhau",
      aspectRatio: "square",
      caption: "Gentle whispers",
      layoutType: "overlap",
    },
    {
      id: "g4",
      src: "/image/wedding/T_T00699.JPG",
      alt: "Cùng bước trên lễ đường",
      aspectRatio: "landscape",
      caption: "Walking towards forever",
      layoutType: "full",
    },
    {
      id: "g5",
      src: "/image/wedding/T_T00780.JPG",
      alt: "Tay trong tay",
      aspectRatio: "portrait",
      caption: "Holding hand through seasons",
      layoutType: "polaroid",
    },
    {
      id: "g6",
      src: "/image/wedding/T_T00817.JPG",
      alt: "Nụ cười rạng rỡ",
      aspectRatio: "portrait",
      caption: "Pure joy & laughter",
      layoutType: "polaroid",
    },
    {
      id: "g7",
      src: "/image/wedding/T_T01187.JPG",
      alt: "Khoảnh khắc lãng mạn",
      aspectRatio: "landscape",
      caption: "Under the golden light",
      layoutType: "editorial-strip",
    },
    {
      id: "g8",
      src: "/image/wedding/T_T00446.JPG",
      alt: "Nàng thơ trong tà váy cưới",
      aspectRatio: "portrait",
      caption: "The elegant bride",
      layoutType: "portrait-tall",
    },
  ],
  loveQuote: {
    title: "ALL OF ME LOVES ALL OF YOU",
    highlight: "Love",
    content:
      "Khi nhận ra rằng mình muốn dành cả quãng đời còn lại bên một người, chúng ta chỉ mong hành trình ấy bắt đầu sớm hơn một chút. Tình yêu không phải là đích đến, mà là từng bước đi cùng nhau – có lúc bình yên, có khi thử thách, nhưng mỗi chặng đường đều dạy chúng ta nhiều điều.",
    author: "Quốc Du & Phương Ly",
    backgroundImage: "/image/wedding/T_T00859.JPG",
  },
  gift: {
    title: "HỘP MỪNG CƯỚI",
    description: "Sự hiện diện của quý khách là niềm vinh hạnh lớn nhất cho gia đình chúng tôi. Nếu quý khách có nhã ý gửi tặng món quà chúc phúc từ xa, xin vui lòng gửi về thông tin dưới đây.",
    accounts: [
      {
        bankName: "Techcombank",
        accountNumber: "19036888888888",
        accountHolder: "QUOC DU",
        branch: "Quảng Ninh",
        role: "groom",
        title: "Mừng Cưới Chú Rể (Quốc Du)",
        qrCodeImage: "https://api.vietqr.io/image/970407-19036888888888-compact.png?accountName=QUOC%20DU&amount=0",
      },
      {
        bankName: "Vietcombank",
        accountNumber: "998877665544",
        accountHolder: "PHUONG LY",
        branch: "Quảng Ninh",
        role: "bride",
        title: "Mừng Cưới Cô Dâu (Phương Ly)",
        qrCodeImage: "https://api.vietqr.io/image/970436-998877665544-compact.png?accountName=PHUONG%20LY&amount=0",
      },
    ],
  },
  music: {
    src: "/audio/wedding-song.mp3",
    title: "Đoạn kết (Happy Ending)",
    artist: "Em Ellata",
    autoPlay: true,
  },
  closing: {
    thankYouText: "THANK YOU",
    message: "Cảm ơn bạn đã luôn là một phần đặc biệt trong câu chuyện tình yêu của chúng tôi. Hẹn gặp lại bạn trong ngày hạnh phúc nhất!",
    image: "/image/wedding/T_T00699.JPG",
  },
};
